//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

DEFINE_GUID(CLSID_CSample, 0x11b8b3b5, 0xf0e7, 0x4569, 0xb0, 0xd1, 0x1c, 0x5d, 0x2a, 0x5e, 0x78, 0xd9);
